Hidden Markov Model prototype Using the Baum-Welch Algorithm to estimate Hidden Markov Model parameters.

This notebook implements the verbatim example from the hidden_markov Python package.

In [1]:
import numpy as np
from hidden_markov import hmm

Initialize states, estimates for hidden state probabilities, transition probabilities, emission probabilitys (probabilities of observables given state).

In [2]:
hidden_states = ('s', 't')
observable_states = ('A', 'B', 'C')

# other model parameters
# probabilities for the initial state
initial_state_prob = np.matrix('0.5, 0.5')

# hidden state transition probabilities
transition_prob_matrix = np.matrix('0.6 0.4; 0.3 0.7')

# emission probabilities assoc. with the observables
emission_prob_matrix = np.matrix('0.3, 0.6, 0.1; 0.4, 0.5, 0.1')

Create the HMM object

In [3]:
learn_model = hmm(hidden_states, observable_states, initial_state_prob, transition_prob_matrix, emission_prob_matrix)

Create a series of observations to train the model on

In [4]:
# generate some observations to fit/train the model
obs1 = ('A', 'B', 'B', 'A', 'C')
obs2 = ('B', 'A', 'B', 'C')
#obs3 = ('played game', 'test score < 85')
#obs4 = ('took content 2', 'took content 1', 'test score >= 85')
#obs5 = ('took content 1', 'took content 2', 'test score >= 85')

# need observation counts observations as tuples 
observation_counts = [10, 20]
observations_tuple = [obs1, obs2]

Train/fit the model

In [5]:
emission, transition, start = learn_model.train_hmm(observations_tuple, 1000, observation_counts)

NOTE:  Patched train_hmm().


In [6]:
print 'emission probs: \n', emission
print '\ntransition matrix: \n', transition
print '\nstart: \n', start

emission probs: 
[[0.28686024 0.50121916 0.21192059]
 [0.31089155 0.43814946 0.25095899]]

transition matrix: 
[[0.58756791 0.41243209]
 [0.29844668 0.70155332]]

start: 
[[0.50910984 0.49089016]]


Test the model