# Hidden Markov Model prototype 

Uses the Baum-Welch Algorithm to estimate Hidden Markov Model parameters.
Two hidden states are constructed, 5 observable states are used, along with initial transition and emissions probabilities 
to create the HMM model.  Then, a series of observed states are used to develop estimates for the initial probabilities, transition probabilities, and emission probabilities.

Numpy is required

Note that you will need to the code at https://github.com/rahul13ramesh/hidden_markov with the pull request submitted by  4caead3

In [1]:
import numpy as np
from hidden_markov import hmm

Initialize states, estimates for hidden state probabilities, transition probabilities, emission probabilitys (probabilities of observables given state).

In [2]:
hidden_states = ('not mastered', 'mastered')
observable_states = ('took content 1', 'took content 2', 'played game', 'test score < 85', 'test score >= 85')

# other model parameters
# probabilities for the initial state
initial_state_prob = np.matrix('0.9 0.1')

# hidden state transition probabilities
transition_prob_matrix = np.matrix('0.5 0.5; 0.15 0.85')

# emission probabilities assoc. with the observables
emission_prob_matrix = np.matrix('0.2, 0.1, 0.3, 0.3, 0.1; 0.05, 0.1, 0.1, 0.05, 0.7')

Create the HMM object

In [4]:
learn_model = hmm(hidden_states, observable_states, initial_state_prob, transition_prob_matrix, emission_prob_matrix)

Create a series of observations to train the model on

In [5]:
# generate some observations to fit/train the model
obs1 = ('took content 1', 'took content 2', 'played game', 'test score >= 85')
obs2 = ('took content 1', 'played game', 'test score < 85')
obs3 = ('played game', 'test score < 85')
obs4 = ('took content 2', 'took content 1', 'test score >= 85')
obs5 = ('took content 1', 'took content 2', 'test score >= 85')

# need observation counts observations as tuples 
observation_counts = [10, 10, 10, 10, 10]
observations_tuple = [obs1, obs2, obs3, obs4, obs5]

Train/fit the model

In [6]:
emission, transition, start = learn_model.train_hmm(observations_tuple, 1000, observation_counts)

NOTE:  Patched train_hmm().


In [7]:
print 'emission probs: \n', emission
print '\ntransition matrix: \n', transition
print '\nstart: \n', start

emission probs: 
[[0.40210093 0.23647834 0.24241179 0.09601713 0.02299182]
 [0.0316926  0.09892588 0.14299276 0.31757846 0.40881031]]

transition matrix: 
[[0.48461144 0.51538856]
 [0.09946943 0.90053057]]

start: 
[[0.98874889 0.01125111]]


Instatiate model with learned parameters

In [8]:
trained_model = hmm(hidden_states, observable_states, start, transition, emission)

Run various observation sequences using the forward algorithm to get probability of occurrence

In [9]:
obs = ('played game', 'test score < 85')
prob = trained_model.forward_algo(obs)
print prob

0.05085888148572142


In [10]:
obs[0]

'played game'